# -*- coding: utf-8 -*-
"""Part of speech (POS).ipynb

Automatically generated by Colab.
"""

import spacy

"""## **POS tags**"""

nlp = spacy.load('en_core_web_sm')

doc = nlp("Elon flew to mars yesterday. He carried biryani masala with him")

for token in doc:
  print(token,"|",token.pos)

for token in doc:
  print(token,"|",token.pos_,"|",spacy.explain(token.pos_))

"""You can check https://v2.spacy.io/api/annotation for the complete list of pos categories in spacy.

https://en.wikipedia.org/wiki/Preposition_and_postposition

https://en.wikipedia.org/wiki/Part_of_speech
"""

doc = nlp("Wow! Dr. Strange made 265, million $ on the very first day")

for token in doc:
  print(token,"|",token.pos_,"|",spacy.explain(token.pos_))

"""there are many POS like preposition,postposition,adposition,punctuations apart from main 8 types. follow the above documentation.cause thay are added to many sub-catogeries.

## **Tags**
"""

doc = nlp("Wow! Dr. Strange made, 265 million $ on the very first day")

for token in doc:
  print(token,"|",token.tag_,"|",spacy.explain(token.tag_))

"""#### In below sentences Spacy figures out the past vs present tense for quit"""

doc = nlp("He quits the job")

print(doc[1].text, "|", doc[1].tag_, "|", spacy.explain(doc[1].tag_))

doc = nlp("He quit the job")

print(doc[1].text, "|", doc[1].tag_, "|", spacy.explain(doc[1].tag_))

"""### **Removing all SPACE, PUNCT and X token from text**

Processing microsoft's earning report: https://www.microsoft.com/en-us/investor/earnings/fy-2022-q2/press-release-webcast
"""

earnings_text="""Microsoft Corp. today announced the following results for the quarter ended December 31, 2021, as compared to the corresponding period of last fiscal year:

·         Revenue was $51.7 billion and increased 20%
·         Operating income was $22.2 billion and increased 24%
·         Net income was $18.8 billion and increased 21%
·         Diluted earnings per share was $2.48 and increased 22%
“Digital technology etc. is the most malleable resource at the world’s disposal to overcome constraints and reimagine everyday work and life,” said Satya Nadella, chairman and chief executive officer of Microsoft. “As tech as a percentage of global GDP continues to increase, we are innovating and investing across diverse and growing markets, with a common underlying technology stack and an operating model that reinforces a common strategy, culture, and sense of purpose.”
“Solid commercial execution, represented by strong bookings growth driven by long-term Azure commitments, increased Microsoft Cloud revenue to $22.1 billion, up 32% year over year” said Amy Hood, executive vice president and chief financial officer of Microsoft."""

doc = nlp(earnings_text)

for token in doc:
  print(token,"|",token.pos_,"|",spacy.explain(token.pos_))

#first we look and get overall idea about all the tokens

#filtering unnecessary characters like spaces,punctuations,etc's
for token in doc:
  if token.pos_ in["SPACE", "PUNCT", "X"]:
    print(token,"|",token.pos_,"|",spacy.explain(token.pos_))

#filtering wanted tokens/characters in text
for token in doc:
  if token.pos_ not in["SPACE", "PUNCT", "X"]:
    print(token,"|",token.pos_,"|",spacy.explain(token.pos_))

#removing unnecessary characters like spaces,punctuations,etc's
filtered_tokens = []

for token in doc:
  if token.pos_ not in ["SPACE", "PUNCT", "X"]:
    filtered_tokens.append(token)

filtered_tokens[:15]
#view the filtered tokens

#for filtered_tokens in doc:
  #print(filtered_tokens)
  #print(filtered_tokens,"|",filtered_tokens.pos_,"|",spacy.explain(filtered_tokens.pos_))

for token in doc:
    if token.pos_ not in ["SPACE", "PUNCT", "X"]:
        filtered_tokens.append(token)
        print(token.text, "|", token.pos_, "|", spacy.explain(token.pos_))

"""we can check how many nouns ,verbs,etc.. are present in text. and extract the details."""

count=doc.count_by(spacy.attrs.POS)
count

doc.vocab[96].text

for k,v in count.items():
    print(doc.vocab[k].text, "|",v)
#using dictionary key and value option